### ISSUE TITLE
Add a progress bar to load_cfb_pbp

### ISSUE THREAD

**Issue by christophermclement** [sportsdataverse/sportsdataverse-py#10]
Obviously, this function takes quite a while to bring in, long enough that it leaves the user uncertain if it's still working properly or if something has frozen. A progress bar would be a nice touch to let the user know that it's still going well, and also give a ballpark on how much longer he'll be waiting.

**Comment by saiemgilani** [comment]
true, i planned on tqdm'ing some stuff like this in near-future iterations
