### ISSUE TITLE
Cannot pull 2021 data from load_cfb_pbp

### ISSUE THREAD

**Issue by JayTheriault** [sportsdataverse/sportsdataverse-py#22]
Trying to access pbp data for the 2021 season leads to a HTTPError. Is there any way to make sure the data is up-to-date? I would love to be able to utilize this package during the season as well. Thank you!

**Comment by armstjc** [comment]
JayTheriault,

Do you still have this issue when running the latest version of sportsdataverse-py?

**Comment by JayTheriault** [comment]
This issue still persists. I looked at the code and it seems to be trying to pull data from a parquet file located here https://github.com/sportsdataverse/cfbfastR-data/tree/main/pbp/parquet which does not exist for the 2021 season

**Comment by JayTheriault** [comment]
Hi, I was wondering if there were any updates? Thanks!

**Comment by saiemgilani** [comment]
This should be fixed now.
