### ISSUE TITLE
404 error loading nfl pbp

### ISSUE THREAD

**Issue by wparry22** [sportsdataverse/sportsdataverse-py#46]
![image](https://user-images.githubusercontent.com/15950797/190184104-2a676b0e-f232-45ca-8bdd-946034ed385e.png)

**Comment by saiemgilani** [comment]
closed by #45

**Comment by wparry22** [comment]
Thanks, Saiem - great timing!

**Comment by saiemgilani** [comment]
> Thanks, Saiem - great timing!

Look at all these [loaders](https://py.sportsdataverse.org/docs/nfl/)
