### ISSUE TITLE
404 Error in teams

### ISSUE THREAD

**Issue by christophermclement** [sportsdataverse/sportsdataverse-py#7]
When calling cfb_teams_frame = sportsdataverse.cfb.load_cfb_team_info(seasons=range(2002, 2022)) I get a 404. It works with any other years. Same error comes if I set "seasons=[2021]".

**Comment by armstjc** [comment]
![image](https://user-images.githubusercontent.com/70788681/176789895-18ebd0c6-564c-4683-945d-ee5f316ba13e.png)
Issue is no longer present in the most recent build of sportsdataverse-py.
